# Generated by Django 4.1.5 on 2023-04-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('cardno', models.CharField(default='', max_length=100)),
                ('expm', models.CharField(default='', max_length=100)),
                ('cvv', models.CharField(default='', max_length=100)),
                ('expy', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
