# Generated by Django 4.1.5 on 2023-04-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bankdetails_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bankdetails',
        ),
    ]
