# Generated by Django 4.1.5 on 2023-05-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
