# Generated by Django 4.1.5 on 2023-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_list',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
