# Generated by Django 4.1.5 on 2023-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_events_list_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_list',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='events_list',
            name='rules',
            field=models.TextField(default=''),
        ),
    ]
