# Generated by Django 4.1.5 on 2023-05-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_booking_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
