# Generated by Django 4.1.5 on 2023-06-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
