# Generated by Django 4.1.5 on 2023-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.FloatField(default=0.0),
        ),
    ]
