# Generated by Django 4.1.5 on 2023-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.CharField(max_length=200),
        ),
    ]
